### ISSUE TITLE
Das Programm wirft am Anfang Fehler, wenn man eine leere DB hat

### ISSUE THREAD

**Issue by Tabisch** [Tabisch/WHS-DBI#1]
Was musste man nochmal machen, um das zu fixen ?

PS C:\Users\Tobias\Downloads> java.exe -jar .\pa9-1.0.1-jar-with-dependencies.jar -db "benchmark" -n 100 -pool_size 5 -host localhost -user dbi -password dbi_pass -reset
[2022-12-16 17:08:05] [INFORMATION]
Host: localhost
Datenbank: benchmark
n: 100

Batch Size: 1000
Pool Size: 5
Fast Mode: false

[2022-12-16 17:08:05] [INFORMATION] Bereite 5 parallele Verbindungen vor...
[2022-12-16 17:08:05] [INFORMATION] Reset und Initialisiere Datenbank
[2022-12-16 17:08:05] [INFORMATION] raeume Datenbank auf...
[2022-12-16 17:08:06] [INFORMATION] Zeitmessung beginnt jetzt!
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO accounts(accid, name, balance, branchid, address)
VALUES(1001, 'AAAAAAAAAAAAAAAAAAAA', 0, 97, 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA') was aborted: ERROR: insert or update on table "accounts" violates foreign key constraint "accounts_branchid_fkey"
  Detail: Key (branchid)=(97) is not present in table "branches".  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:186)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:571)
        at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
        at io.github.dbi31.pa9.setup.DBInit.lambda$2(DBInit.java:79)
        at io.github.dbi31.pa9.util.ParallelConnectionManager.runJob(ParallelConnectionManager.java:88)
        at io.github.dbi31.pa9.util.ParallelConnectionManager$WorkerThread.run(ParallelConnectionManager.java:148)
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "accounts" violates foreign key constraint "accounts_branchid_fkey"
  Detail: Key (branchid)=(97) is not present in table "branches".
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2099)
        at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1456)
        at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1481)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:546)
        ... 6 more
[2022-12-16 17:08:06] [INFORMATION] INSERT branches 0-100 abgeschlossen!
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO accounts(accid, name, balance, branchid, address)
VALUES(2001, 'AAAAAAAAAAAAAAAAAAAA', 0, 21, 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA') was aborted: ERROR: insert or update on table "accounts" violates foreign key constraint "accounts_branchid_fkey"
  Detail: Key (branchid)=(21) is not present in table "branches".  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:186)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:571)
        at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
        at io.github.dbi31.pa9.setup.DBInit.lambda$2(DBInit.java:79)
        at io.github.dbi31.pa9.util.ParallelConnectionManager.runJob(ParallelConnectionManager.java:88)
        at io.github.dbi31.pa9.util.ParallelConnectionManager$WorkerThread.run(ParallelConnectionManager.java:148)
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "accounts" violates foreign key constraint "accounts_branchid_fkey"
  Detail: Key (branchid)=(21) is not present in table "branches".
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2099)
        at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1456)
        at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1481)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:546)
        ... 6 more
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO accounts(accid, name, balance, branchid, address)
VALUES(1, 'AAAAAAAAAAAAAAAAAAAA', 0, 100, 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA') was aborted: ERROR: insert or update on table "accounts" violates foreign key constraint "accounts_branchid_fkey"
  Detail: Key (branchid)=(100) is not present in table "branches".  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:186)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:571)
        at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
        at io.github.dbi31.pa9.setup.DBInit.lambda$2(DBInit.java:79)
        at io.github.dbi31.pa9.util.ParallelConnectionManager.runJob(ParallelConnectionManager.java:88)
        at io.github.dbi31.pa9.util.ParallelConnectionManager$WorkerThread.run(ParallelConnectionManager.java:148)
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "accounts" violates foreign key constraint "accounts_branchid_fkey"
  Detail: Key (branchid)=(100) is not present in table "branches".
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2099)
        at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1456)
        at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1481)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:546)
        ... 6 more
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO accounts(accid, name, balance, branchid, address)
VALUES(3001, 'AAAAAAAAAAAAAAAAAAAA', 0, 44, 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA') was aborted: ERROR: insert or update on table "accounts" violates foreign key constraint "accounts_branchid_fkey"
  Detail: Key (branchid)=(44) is not present in table "branches".  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:186)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:571)
        at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
        at io.github.dbi31.pa9.setup.DBInit.lambda$2(DBInit.java:79)
        at io.github.dbi31.pa9.util.ParallelConnectionManager.runJob(ParallelConnectionManager.java:88)
        at io.github.dbi31.pa9.util.ParallelConnectionManager$WorkerThread.run(ParallelConnectionManager.java:148)
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "accounts" violates foreign key constraint "accounts_branchid_fkey"
  Detail: Key (branchid)=(44) is not present in table "branches".
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2099)
        at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1456)
        at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1481)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:546)
        ... 6 more
[2022-12-16 17:08:06] [INFORMATION] INSERT accounts 4000-5000 abgeschlossen!

**Comment by Tabisch** [comment]
falsches repo sry
